name: cog_model_env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - numpy=2.2.1
  - pandas=3.0.0
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - scipy
  - pytorch=2.10.0
  - torchvision=0.25.0
  - pip:
    - cmdstanpy=1.3.0
    - tqdm=4.67.1